// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKUKcUpfLqSFb4hZT_QfKILuiVCqXYWu4',
    appId: '1:150527541857:web:YOUR_WEB_APP_ID',
    messagingSenderId: '150527541857',
    projectId: 'scoutmena-app',
    authDomain: 'scoutmena-app.firebaseapp.com',
    storageBucket: 'scoutmena-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUKcUpfLqSFb4hZT_QfKILuiVCqXYWu4',
    appId: '1:150527541857:android:905dd29d707b163cd8e020',
    messagingSenderId: '150527541857',
    projectId: 'scoutmena-app',
    storageBucket: 'scoutmena-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKUKcUpfLqSFb4hZT_QfKILuiVCqXYWu4',
    appId: '1:150527541857:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '150527541857',
    projectId: 'scoutmena-app',
    storageBucket: 'scoutmena-app.firebasestorage.app',
    iosBundleId: 'com.scoutmena.app',
  );
}
